### ISSUE TITLE
Genie.jl: Julia Web Framework

### ISSUE THREAD

**Issue by Diaga** [MLH-Fellowship/CodeVidLive#21]
Genie is going to be as a middleman for communication between flutter app and prediction model through API. 
Also, exposes endpoints for Use Case 3 in #1.

Repo link [here](https://github.com/GenieFramework/Genie.jl).

### Progress
- [x] Setup Genie
- [x] Provide dummy response for maps portion using #4 
- [x] Provide dummy response for visualization using #6 
- [ ] Update dummy responses with actual data from db using #7

**Comment by Diaga** [comment]
### Endpoint
api/prediction

### Query Params
- longitude (required)
- latitude (required)

### Method
GET

### Response
``` json
[
   {
      "requested":[
         {
            "latitude":-81.46996
         },
         {
            "longitude":-63.53797
         },
         {
            "chance":0.59
         }
      ]
   },
   {
      "nearby":[
         [
            {
               "latitude":-81.46996
            },
            {
               "longitude":-63.53797
            },
            {
               "chance":0.59
            }
         ],
         [
            {
               "latitude":-81.46996
            },
            {
               "longitude":-63.53797
            },
            {
               "chance":0.59
            }
         ],
         [
            {
               "latitude":-81.46996
            },
            {
               "longitude":-63.53797
            },
            {
               "chance":0.59
            }
         ]
      ]
   }
]
```
#### Questions
@michiboo Does the following JSON provide all the info you might need for use case #1 and #2 in maps portion?
@RashikaKarki I think you will need a time series for the specific location to draw the visualization graphs, is that correct?
@zzj0402 We will get this chance parameter from the model right, given input of longitude and latitude, right?

**Comment by michiboo** [comment]
@Diaga  Yes I think LatLong points is enough

**Comment by Diaga** [comment]
> @Diaga Yes I think LatLong points is enough

We might need the chance to maybe add intensity to the "red" color on the map overlay. Does that work?

**Comment by michiboo** [comment]
@Diaga  so from client side we just need to post lat/long and in response receive chance and higher the chance the more red for the line of circle. So it work.

But the things is should we use the user point as center of circle or the response's point as centre of circle? Also how many lat/long points should be return from the model? Just one or list of points?
I would suggest it return a radius as well from the model if it is possible. or we can just convert it in the genie/in flutter client.  So higher chance == larger radius == more red?

**Comment by RashikaKarki** [comment]
Yes, timestamp and total no. of infected people will be needed for the visualization.

**Comment by Diaga** [comment]
> @Diaga so from client side we just need to post lat/long and in response receive chance and higher the chance the more red for the line of circle. So it work.

Yes, exactly.

> But the things is should we use the user point as center of circle or the response's point as centre of circle?

In an ideal situation, the user point would be the same as response point. I think this will depend on data but we should go with response's point as center.
Because realistically, the data cannot cover every road on the map. And I don't think our model predicts for locations about which we have no data.

> Also how many lat/long points should be return from the model? Just one or list of points?

There are two main keys for the json.
- "requested": This will return just one point closest to where the user requested.
- "nearby": This will return multiple points (dynamic, could be 0 upto a maximum of 5?) near the user's requested point, upto a specified distance threshold like 1km. This way the user can see hotspots near his location as well.

> I would suggest it return a radius as well from the model if it is possible. or we can just convert it in the genie/in flutter client. So higher chance == larger radius == more red?

Great! I think this formula would be better to calculate radius. We may have to experiment to see what works best. 
Let's do it on the flutter side so we can easily see changes on hot reload.

**Comment by Diaga** [comment]
> Yes, timestamp and total no. of infected people will be needed for the visualization.

Got it.
